//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace LightSwitchApplication.Implementation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ConvictsData : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ConvictsData object using the connection string found in the 'ConvictsData' section of the application configuration file.
        /// </summary>
        public ConvictsData() : base("name=ConvictsData", "ConvictsData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ConvictsData object.
        /// </summary>
        public ConvictsData(string connectionString) : base(connectionString, "ConvictsData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ConvictsData object.
        /// </summary>
        public ConvictsData(EntityConnection connection) : base(connection, "ConvictsData")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Convict> Convicts
        {
            get
            {
                if ((_Convicts == null))
                {
                    _Convicts = base.CreateObjectSet<Convict>("Convicts");
                }
                return _Convicts;
            }
        }
        private ObjectSet<Convict> _Convicts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Leaderboard> Leaderboards
        {
            get
            {
                if ((_Leaderboards == null))
                {
                    _Leaderboards = base.CreateObjectSet<Leaderboard>("Leaderboards");
                }
                return _Leaderboards;
            }
        }
        private ObjectSet<Leaderboard> _Leaderboards;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PaymentRecord> PaymentRecords
        {
            get
            {
                if ((_PaymentRecords == null))
                {
                    _PaymentRecords = base.CreateObjectSet<PaymentRecord>("PaymentRecords");
                }
                return _PaymentRecords;
            }
        }
        private ObjectSet<PaymentRecord> _PaymentRecords;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Team> Teams
        {
            get
            {
                if ((_Teams == null))
                {
                    _Teams = base.CreateObjectSet<Team>("Teams");
                }
                return _Teams;
            }
        }
        private ObjectSet<Team> _Teams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Convicts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConvicts(Convict convict)
        {
            base.AddObject("Convicts", convict);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Leaderboards EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLeaderboards(Leaderboard leaderboard)
        {
            base.AddObject("Leaderboards", leaderboard);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PaymentRecords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPaymentRecords(PaymentRecord paymentRecord)
        {
            base.AddObject("PaymentRecords", paymentRecord);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Teams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTeams(Team team)
        {
            base.AddObject("Teams", team);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Convict")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Convict : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Convict object.
        /// </summary>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        /// <param name="modifiedDate">Initial value of the ModifiedDate property.</param>
        /// <param name="total">Initial value of the Total property.</param>
        public static Convict CreateConvict(global::System.String email, global::System.DateTime createDate, global::System.DateTime modifiedDate, global::System.String total)
        {
            Convict convict = new Convict();
            convict.Email = email;
            convict.CreateDate = createDate;
            convict.ModifiedDate = modifiedDate;
            convict.Total = total;
            return convict;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                if (_Email != value)
                {
                    OnEmailChanging(value);
                    ReportPropertyChanging("Email");
                    _Email = value;
                    ReportPropertyChanged("Email");
                    OnEmailChanged();
                }
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ConvictCode
        {
            get
            {
                return _ConvictCode;
            }
            set
            {
                OnConvictCodeChanging(value);
                ReportPropertyChanging("ConvictCode");
                _ConvictCode = value;
                ReportPropertyChanged("ConvictCode");
                OnConvictCodeChanged();
            }
        }
        private global::System.String _ConvictCode;
        partial void OnConvictCodeChanging(global::System.String value);
        partial void OnConvictCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = value;
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProfileURL
        {
            get
            {
                return _ProfileURL;
            }
            set
            {
                OnProfileURLChanging(value);
                ReportPropertyChanging("ProfileURL");
                _ProfileURL = value;
                ReportPropertyChanged("ProfileURL");
                OnProfileURLChanged();
            }
        }
        private global::System.String _ProfileURL;
        partial void OnProfileURLChanging(global::System.String value);
        partial void OnProfileURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TeamCode
        {
            get
            {
                return _TeamCode;
            }
            set
            {
                OnTeamCodeChanging(value);
                ReportPropertyChanging("TeamCode");
                _TeamCode = value;
                ReportPropertyChanged("TeamCode");
                OnTeamCodeChanged();
            }
        }
        private global::System.String _TeamCode;
        partial void OnTeamCodeChanging(global::System.String value);
        partial void OnTeamCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TeamType
        {
            get
            {
                return _TeamType;
            }
            set
            {
                OnTeamTypeChanging(value);
                ReportPropertyChanging("TeamType");
                _TeamType = value;
                ReportPropertyChanged("TeamType");
                OnTeamTypeChanged();
            }
        }
        private global::System.String _TeamType;
        partial void OnTeamTypeChanging(global::System.String value);
        partial void OnTeamTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = value;
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = value;
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = value;
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private global::System.String _Total;
        partial void OnTotalChanging(global::System.String value);
        partial void OnTotalChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Leaderboard")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Leaderboard : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Leaderboard object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Leaderboard CreateLeaderboard(global::System.Int32 id)
        {
            Leaderboard leaderboard = new Leaderboard();
            leaderboard.ID = id;
            return leaderboard;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = value;
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ConvictCode
        {
            get
            {
                return _ConvictCode;
            }
            set
            {
                OnConvictCodeChanging(value);
                ReportPropertyChanging("ConvictCode");
                _ConvictCode = value;
                ReportPropertyChanged("ConvictCode");
                OnConvictCodeChanged();
            }
        }
        private Nullable<global::System.Int32> _ConvictCode;
        partial void OnConvictCodeChanging(Nullable<global::System.Int32> value);
        partial void OnConvictCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TeamCode
        {
            get
            {
                return _TeamCode;
            }
            set
            {
                OnTeamCodeChanging(value);
                ReportPropertyChanging("TeamCode");
                _TeamCode = value;
                ReportPropertyChanged("TeamCode");
                OnTeamCodeChanged();
            }
        }
        private Nullable<global::System.Int32> _TeamCode;
        partial void OnTeamCodeChanging(Nullable<global::System.Int32> value);
        partial void OnTeamCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = value;
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private Nullable<global::System.Int32> _Total;
        partial void OnTotalChanging(Nullable<global::System.Int32> value);
        partial void OnTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ConvictName
        {
            get
            {
                return _ConvictName;
            }
            set
            {
                OnConvictNameChanging(value);
                ReportPropertyChanging("ConvictName");
                _ConvictName = value;
                ReportPropertyChanged("ConvictName");
                OnConvictNameChanged();
            }
        }
        private global::System.String _ConvictName;
        partial void OnConvictNameChanging(global::System.String value);
        partial void OnConvictNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TeamName
        {
            get
            {
                return _TeamName;
            }
            set
            {
                OnTeamNameChanging(value);
                ReportPropertyChanging("TeamName");
                _TeamName = value;
                ReportPropertyChanged("TeamName");
                OnTeamNameChanged();
            }
        }
        private global::System.String _TeamName;
        partial void OnTeamNameChanging(global::System.String value);
        partial void OnTeamNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegistrationType
        {
            get
            {
                return _RegistrationType;
            }
            set
            {
                OnRegistrationTypeChanging(value);
                ReportPropertyChanging("RegistrationType");
                _RegistrationType = value;
                ReportPropertyChanged("RegistrationType");
                OnRegistrationTypeChanged();
            }
        }
        private global::System.String _RegistrationType;
        partial void OnRegistrationTypeChanging(global::System.String value);
        partial void OnRegistrationTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TeamType
        {
            get
            {
                return _TeamType;
            }
            set
            {
                OnTeamTypeChanging(value);
                ReportPropertyChanging("TeamType");
                _TeamType = value;
                ReportPropertyChanged("TeamType");
                OnTeamTypeChanged();
            }
        }
        private global::System.String _TeamType;
        partial void OnTeamTypeChanging(global::System.String value);
        partial void OnTeamTypeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="PaymentRecord")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PaymentRecord : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PaymentRecord object.
        /// </summary>
        /// <param name="paymentID">Initial value of the paymentID property.</param>
        /// <param name="amount">Initial value of the amount property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        /// <param name="anonymous">Initial value of the Anonymous property.</param>
        /// <param name="transactionID">Initial value of the TransactionID property.</param>
        /// <param name="invoiceID">Initial value of the InvoiceID property.</param>
        public static PaymentRecord CreatePaymentRecord(global::System.Int32 paymentID, global::System.Double amount, global::System.DateTime createDate, global::System.String message, global::System.Boolean anonymous, global::System.Int32 transactionID, global::System.Int32 invoiceID)
        {
            PaymentRecord paymentRecord = new PaymentRecord();
            paymentRecord.paymentID = paymentID;
            paymentRecord.amount = amount;
            paymentRecord.CreateDate = createDate;
            paymentRecord.Message = message;
            paymentRecord.Anonymous = anonymous;
            paymentRecord.TransactionID = transactionID;
            paymentRecord.InvoiceID = invoiceID;
            return paymentRecord;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 paymentID
        {
            get
            {
                return _paymentID;
            }
            set
            {
                if (_paymentID != value)
                {
                    OnpaymentIDChanging(value);
                    ReportPropertyChanging("paymentID");
                    _paymentID = value;
                    ReportPropertyChanged("paymentID");
                    OnpaymentIDChanged();
                }
            }
        }
        private global::System.Int32 _paymentID;
        partial void OnpaymentIDChanging(global::System.Int32 value);
        partial void OnpaymentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PayerEmail
        {
            get
            {
                return _PayerEmail;
            }
            set
            {
                OnPayerEmailChanging(value);
                ReportPropertyChanging("PayerEmail");
                _PayerEmail = value;
                ReportPropertyChanged("PayerEmail");
                OnPayerEmailChanged();
            }
        }
        private global::System.String _PayerEmail;
        partial void OnPayerEmailChanging(global::System.String value);
        partial void OnPayerEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double amount
        {
            get
            {
                return _amount;
            }
            set
            {
                OnamountChanging(value);
                ReportPropertyChanging("amount");
                _amount = value;
                ReportPropertyChanged("amount");
                OnamountChanged();
            }
        }
        private global::System.Double _amount;
        partial void OnamountChanging(global::System.Double value);
        partial void OnamountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ConvictEmail
        {
            get
            {
                return _ConvictEmail;
            }
            set
            {
                OnConvictEmailChanging(value);
                ReportPropertyChanging("ConvictEmail");
                _ConvictEmail = value;
                ReportPropertyChanged("ConvictEmail");
                OnConvictEmailChanged();
            }
        }
        private global::System.String _ConvictEmail;
        partial void OnConvictEmailChanging(global::System.String value);
        partial void OnConvictEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TeamCode
        {
            get
            {
                return _TeamCode;
            }
            set
            {
                OnTeamCodeChanging(value);
                ReportPropertyChanging("TeamCode");
                _TeamCode = value;
                ReportPropertyChanged("TeamCode");
                OnTeamCodeChanged();
            }
        }
        private global::System.String _TeamCode;
        partial void OnTeamCodeChanging(global::System.String value);
        partial void OnTeamCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaymentType
        {
            get
            {
                return _PaymentType;
            }
            set
            {
                OnPaymentTypeChanging(value);
                ReportPropertyChanging("PaymentType");
                _PaymentType = value;
                ReportPropertyChanged("PaymentType");
                OnPaymentTypeChanged();
            }
        }
        private global::System.String _PaymentType;
        partial void OnPaymentTypeChanging(global::System.String value);
        partial void OnPaymentTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = value;
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = value;
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DonorName
        {
            get
            {
                return _DonorName;
            }
            set
            {
                OnDonorNameChanging(value);
                ReportPropertyChanging("DonorName");
                _DonorName = value;
                ReportPropertyChanged("DonorName");
                OnDonorNameChanged();
            }
        }
        private global::System.String _DonorName;
        partial void OnDonorNameChanging(global::System.String value);
        partial void OnDonorNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Anonymous
        {
            get
            {
                return _Anonymous;
            }
            set
            {
                OnAnonymousChanging(value);
                ReportPropertyChanging("Anonymous");
                _Anonymous = value;
                ReportPropertyChanged("Anonymous");
                OnAnonymousChanged();
            }
        }
        private global::System.Boolean _Anonymous;
        partial void OnAnonymousChanging(global::System.Boolean value);
        partial void OnAnonymousChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TransactionID
        {
            get
            {
                return _TransactionID;
            }
            set
            {
                OnTransactionIDChanging(value);
                ReportPropertyChanging("TransactionID");
                _TransactionID = value;
                ReportPropertyChanged("TransactionID");
                OnTransactionIDChanged();
            }
        }
        private global::System.Int32 _TransactionID;
        partial void OnTransactionIDChanging(global::System.Int32 value);
        partial void OnTransactionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InvoiceID
        {
            get
            {
                return _InvoiceID;
            }
            set
            {
                OnInvoiceIDChanging(value);
                ReportPropertyChanging("InvoiceID");
                _InvoiceID = value;
                ReportPropertyChanged("InvoiceID");
                OnInvoiceIDChanged();
            }
        }
        private global::System.Int32 _InvoiceID;
        partial void OnInvoiceIDChanging(global::System.Int32 value);
        partial void OnInvoiceIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Team")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Team : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Team object.
        /// </summary>
        /// <param name="teamCode">Initial value of the TeamCode property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        /// <param name="modifiedDate">Initial value of the ModifiedDate property.</param>
        /// <param name="total">Initial value of the Total property.</param>
        public static Team CreateTeam(global::System.String teamCode, global::System.DateTime createDate, global::System.DateTime modifiedDate, global::System.String total)
        {
            Team team = new Team();
            team.TeamCode = teamCode;
            team.CreateDate = createDate;
            team.ModifiedDate = modifiedDate;
            team.Total = total;
            return team;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TeamCode
        {
            get
            {
                return _TeamCode;
            }
            set
            {
                if (_TeamCode != value)
                {
                    OnTeamCodeChanging(value);
                    ReportPropertyChanging("TeamCode");
                    _TeamCode = value;
                    ReportPropertyChanged("TeamCode");
                    OnTeamCodeChanged();
                }
            }
        }
        private global::System.String _TeamCode;
        partial void OnTeamCodeChanging(global::System.String value);
        partial void OnTeamCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TeamName
        {
            get
            {
                return _TeamName;
            }
            set
            {
                OnTeamNameChanging(value);
                ReportPropertyChanging("TeamName");
                _TeamName = value;
                ReportPropertyChanged("TeamName");
                OnTeamNameChanged();
            }
        }
        private global::System.String _TeamName;
        partial void OnTeamNameChanging(global::System.String value);
        partial void OnTeamNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TeamURL
        {
            get
            {
                return _TeamURL;
            }
            set
            {
                OnTeamURLChanging(value);
                ReportPropertyChanging("TeamURL");
                _TeamURL = value;
                ReportPropertyChanged("TeamURL");
                OnTeamURLChanged();
            }
        }
        private global::System.String _TeamURL;
        partial void OnTeamURLChanging(global::System.String value);
        partial void OnTeamURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TeamType
        {
            get
            {
                return _TeamType;
            }
            set
            {
                OnTeamTypeChanging(value);
                ReportPropertyChanging("TeamType");
                _TeamType = value;
                ReportPropertyChanged("TeamType");
                OnTeamTypeChanged();
            }
        }
        private global::System.String _TeamType;
        partial void OnTeamTypeChanging(global::System.String value);
        partial void OnTeamTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = value;
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = value;
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = value;
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private global::System.String _Total;
        partial void OnTotalChanging(global::System.String value);
        partial void OnTotalChanged();

        #endregion

    
    }

    #endregion

    
}
