
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Workspace
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed class DataWorkspace : global::Microsoft.LightSwitch.Framework.Base.DataWorkspace<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of a DataWorkspace.  Changes can be made to data sources in the new instance independent of changes made to data sources in the default DataWorkspace.
        /// </summary>
        public DataWorkspace() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the ConvictsData datasource.  This provides members to query and update data in the data source.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.ConvictsDataService ConvictsData
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ConvictsData);
            }
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspaceDetails<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ConvictsData;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspacePropertySet<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ConvictsDataService> ConvictsData
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ConvictsData) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ConvictsDataService>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ConvictsDataService>.Entry
                    ConvictsData = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ConvictsDataService>.Entry(
                        "ConvictsData",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._ConvictsData_Stub);
                private static void _ConvictsData_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ConvictsDataService>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._ConvictsData, sf);
                }
                 
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ConvictsDataService>.Data _ConvictsData;
            
        }
    
        #endregion
    }
    
    #endregion
    
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the ConvictsData datasource.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ConvictsData : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// This constructor is used for the internal LightSwitch framework. Use DataWorkspace instead.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ConvictsData() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the Convicts entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Convict> Convicts
        {
            get
            {
                return global::LightSwitchApplication.ConvictsData.DetailsClass.GetValue(this, global::LightSwitchApplication.ConvictsData.DetailsClass.PropertySetProperties.Convicts);
            }
        }
        
        /// <summary>
        /// Gets the Leaderboards entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Leaderboard> Leaderboards
        {
            get
            {
                return global::LightSwitchApplication.ConvictsData.DetailsClass.GetValue(this, global::LightSwitchApplication.ConvictsData.DetailsClass.PropertySetProperties.Leaderboards);
            }
        }
        
        /// <summary>
        /// Gets the PaymentRecords entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.PaymentRecord> PaymentRecords
        {
            get
            {
                return global::LightSwitchApplication.ConvictsData.DetailsClass.GetValue(this, global::LightSwitchApplication.ConvictsData.DetailsClass.PropertySetProperties.PaymentRecords);
            }
        }
        
        /// <summary>
        /// Gets the Teams entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Team> Teams
        {
            get
            {
                return global::LightSwitchApplication.ConvictsData.DetailsClass.GetValue(this, global::LightSwitchApplication.ConvictsData.DetailsClass.PropertySetProperties.Teams);
            }
        }
        
        #endregion
    
        #region Queries
    
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Email">
        /// The value of the 'Email' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Convict Convicts_Single(string Email)
        {
            return this.Details.Methods.Convicts_Single.CreateInvocation(Email).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Email">
        /// The value of the 'Email' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Convict Convicts_SingleOrDefault(string Email)
        {
            return this.Details.Methods.Convicts_SingleOrDefault.CreateInvocation(Email).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="ID">
        /// The value of the 'ID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Leaderboard Leaderboards_Single(global::System.Nullable<int> ID)
        {
            return this.Details.Methods.Leaderboards_Single.CreateInvocation(ID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="ID">
        /// The value of the 'ID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Leaderboard Leaderboards_SingleOrDefault(global::System.Nullable<int> ID)
        {
            return this.Details.Methods.Leaderboards_SingleOrDefault.CreateInvocation(ID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="paymentID">
        /// The value of the 'paymentID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.PaymentRecord PaymentRecords_Single(global::System.Nullable<int> paymentID)
        {
            return this.Details.Methods.PaymentRecords_Single.CreateInvocation(paymentID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="paymentID">
        /// The value of the 'paymentID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.PaymentRecord PaymentRecords_SingleOrDefault(global::System.Nullable<int> paymentID)
        {
            return this.Details.Methods.PaymentRecords_SingleOrDefault.CreateInvocation(paymentID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="TeamCode">
        /// The value of the 'TeamCode' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Team Teams_Single(string TeamCode)
        {
            return this.Details.Methods.Teams_Single.CreateInvocation(TeamCode).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="TeamCode">
        /// The value of the 'TeamCode' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Team Teams_SingleOrDefault(string TeamCode)
        {
            return this.Details.Methods.Teams_SingleOrDefault.CreateInvocation(TeamCode).Execute();
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.ConvictsData.DetailsClass.PropertySet, global::LightSwitchApplication.ConvictsData.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
                var initializeMethodEntry = global::LightSwitchApplication.ConvictsData.DetailsClass.MethodSetProperties.Convicts_Single;
                var initializePropertyEntry = global::LightSwitchApplication.ConvictsData.DetailsClass.PropertySetProperties.Convicts;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.ConvictsData.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ConvictsData.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Convict> Convicts_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ConvictsData.DetailsClass.MethodSetProperties.Convicts_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Convict>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Convict> Convicts_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ConvictsData.DetailsClass.MethodSetProperties.Convicts_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Convict>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Leaderboard> Leaderboards_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ConvictsData.DetailsClass.MethodSetProperties.Leaderboards_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Leaderboard>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Leaderboard> Leaderboards_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ConvictsData.DetailsClass.MethodSetProperties.Leaderboards_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Leaderboard>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.PaymentRecord> PaymentRecords_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ConvictsData.DetailsClass.MethodSetProperties.PaymentRecords_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.PaymentRecord>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.PaymentRecord> PaymentRecords_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ConvictsData.DetailsClass.MethodSetProperties.PaymentRecords_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.PaymentRecord>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Team> Teams_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ConvictsData.DetailsClass.MethodSetProperties.Teams_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Team>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Team> Teams_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ConvictsData.DetailsClass.MethodSetProperties.Teams_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Team>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Convict> Convicts
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ConvictsData.DetailsClass.PropertySetProperties.Convicts) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Convict>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Leaderboard> Leaderboards
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ConvictsData.DetailsClass.PropertySetProperties.Leaderboards) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Leaderboard>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.PaymentRecord> PaymentRecords
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ConvictsData.DetailsClass.PropertySetProperties.PaymentRecords) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.PaymentRecord>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Team> Teams
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ConvictsData.DetailsClass.PropertySetProperties.Teams) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Team>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Convict>.Entry
                    Convicts_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Convict>.Entry(
                        "Convicts_Single",
                        global::LightSwitchApplication.ConvictsData.DetailsClass.MethodSetProperties._Convicts_Single_Stub);
                private static void _Convicts_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ConvictsData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Convict>.Data> c, global::LightSwitchApplication.ConvictsData.DetailsClass d, object sf)
                {
                    c(d, ref d._Convicts_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Convict>.Entry
                    Convicts_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Convict>.Entry(
                        "Convicts_SingleOrDefault",
                        global::LightSwitchApplication.ConvictsData.DetailsClass.MethodSetProperties._Convicts_SingleOrDefault_Stub);
                private static void _Convicts_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ConvictsData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Convict>.Data> c, global::LightSwitchApplication.ConvictsData.DetailsClass d, object sf)
                {
                    c(d, ref d._Convicts_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Leaderboard>.Entry
                    Leaderboards_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Leaderboard>.Entry(
                        "Leaderboards_Single",
                        global::LightSwitchApplication.ConvictsData.DetailsClass.MethodSetProperties._Leaderboards_Single_Stub);
                private static void _Leaderboards_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ConvictsData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Leaderboard>.Data> c, global::LightSwitchApplication.ConvictsData.DetailsClass d, object sf)
                {
                    c(d, ref d._Leaderboards_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Leaderboard>.Entry
                    Leaderboards_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Leaderboard>.Entry(
                        "Leaderboards_SingleOrDefault",
                        global::LightSwitchApplication.ConvictsData.DetailsClass.MethodSetProperties._Leaderboards_SingleOrDefault_Stub);
                private static void _Leaderboards_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ConvictsData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Leaderboard>.Data> c, global::LightSwitchApplication.ConvictsData.DetailsClass d, object sf)
                {
                    c(d, ref d._Leaderboards_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.PaymentRecord>.Entry
                    PaymentRecords_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.PaymentRecord>.Entry(
                        "PaymentRecords_Single",
                        global::LightSwitchApplication.ConvictsData.DetailsClass.MethodSetProperties._PaymentRecords_Single_Stub);
                private static void _PaymentRecords_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ConvictsData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.PaymentRecord>.Data> c, global::LightSwitchApplication.ConvictsData.DetailsClass d, object sf)
                {
                    c(d, ref d._PaymentRecords_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.PaymentRecord>.Entry
                    PaymentRecords_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.PaymentRecord>.Entry(
                        "PaymentRecords_SingleOrDefault",
                        global::LightSwitchApplication.ConvictsData.DetailsClass.MethodSetProperties._PaymentRecords_SingleOrDefault_Stub);
                private static void _PaymentRecords_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ConvictsData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.PaymentRecord>.Data> c, global::LightSwitchApplication.ConvictsData.DetailsClass d, object sf)
                {
                    c(d, ref d._PaymentRecords_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Team>.Entry
                    Teams_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Team>.Entry(
                        "Teams_Single",
                        global::LightSwitchApplication.ConvictsData.DetailsClass.MethodSetProperties._Teams_Single_Stub);
                private static void _Teams_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ConvictsData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Team>.Data> c, global::LightSwitchApplication.ConvictsData.DetailsClass d, object sf)
                {
                    c(d, ref d._Teams_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Team>.Entry
                    Teams_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Team>.Entry(
                        "Teams_SingleOrDefault",
                        global::LightSwitchApplication.ConvictsData.DetailsClass.MethodSetProperties._Teams_SingleOrDefault_Stub);
                private static void _Teams_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ConvictsData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Team>.Data> c, global::LightSwitchApplication.ConvictsData.DetailsClass d, object sf)
                {
                    c(d, ref d._Teams_SingleOrDefault, sf);
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Convict>.Entry
                    Convicts = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Convict>.Entry(
                        "Convicts",
                        global::LightSwitchApplication.ConvictsData.DetailsClass.PropertySetProperties._Convicts_Stub);
                private static void _Convicts_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ConvictsData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Convict>.Data> c, global::LightSwitchApplication.ConvictsData.DetailsClass d, object sf)
                {
                    c(d, ref d._Convicts, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Leaderboard>.Entry
                    Leaderboards = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Leaderboard>.Entry(
                        "Leaderboards",
                        global::LightSwitchApplication.ConvictsData.DetailsClass.PropertySetProperties._Leaderboards_Stub);
                private static void _Leaderboards_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ConvictsData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Leaderboard>.Data> c, global::LightSwitchApplication.ConvictsData.DetailsClass d, object sf)
                {
                    c(d, ref d._Leaderboards, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.PaymentRecord>.Entry
                    PaymentRecords = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.PaymentRecord>.Entry(
                        "PaymentRecords",
                        global::LightSwitchApplication.ConvictsData.DetailsClass.PropertySetProperties._PaymentRecords_Stub);
                private static void _PaymentRecords_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ConvictsData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.PaymentRecord>.Data> c, global::LightSwitchApplication.ConvictsData.DetailsClass d, object sf)
                {
                    c(d, ref d._PaymentRecords, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Team>.Entry
                    Teams = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Team>.Entry(
                        "Teams",
                        global::LightSwitchApplication.ConvictsData.DetailsClass.PropertySetProperties._Teams_Stub);
                private static void _Teams_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ConvictsData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Team>.Data> c, global::LightSwitchApplication.ConvictsData.DetailsClass d, object sf)
                {
                    c(d, ref d._Teams, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Convict>.Data _Convicts;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Leaderboard>.Data _Leaderboards;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.PaymentRecord>.Data _PaymentRecords;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Team>.Data _Teams;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Convict>.Data _Convicts_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Convict>.Data _Convicts_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Leaderboard>.Data _Leaderboards_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Leaderboard>.Data _Leaderboards_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.PaymentRecord>.Data _PaymentRecords_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.PaymentRecord>.Data _PaymentRecords_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Team>.Data _Teams_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ConvictsData, global::LightSwitchApplication.ConvictsData.DetailsClass, global::LightSwitchApplication.Team>.Data _Teams_SingleOrDefault;
            
        }
    
        #endregion
    }
    
    #endregion
    
}
