

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class PaymentRecord : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the PaymentRecord entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public PaymentRecord()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public PaymentRecord(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.PaymentRecord> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.PaymentRecord.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PaymentRecord_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PaymentRecord_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int paymentID
        {
            get
            {
                return global::LightSwitchApplication.PaymentRecord.DetailsClass.GetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.paymentID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void paymentID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void paymentID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void paymentID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string PayerEmail
        {
            get
            {
                return global::LightSwitchApplication.PaymentRecord.DetailsClass.GetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.PayerEmail);
            }
            set
            {
                global::LightSwitchApplication.PaymentRecord.DetailsClass.SetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.PayerEmail, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PayerEmail_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PayerEmail_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PayerEmail_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double amount
        {
            get
            {
                return global::LightSwitchApplication.PaymentRecord.DetailsClass.GetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.amount);
            }
            set
            {
                global::LightSwitchApplication.PaymentRecord.DetailsClass.SetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.amount, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void amount_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void amount_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void amount_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ConvictEmail
        {
            get
            {
                return global::LightSwitchApplication.PaymentRecord.DetailsClass.GetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.ConvictEmail);
            }
            set
            {
                global::LightSwitchApplication.PaymentRecord.DetailsClass.SetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.ConvictEmail, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ConvictEmail_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ConvictEmail_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ConvictEmail_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TeamCode
        {
            get
            {
                return global::LightSwitchApplication.PaymentRecord.DetailsClass.GetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.TeamCode);
            }
            set
            {
                global::LightSwitchApplication.PaymentRecord.DetailsClass.SetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.TeamCode, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TeamCode_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TeamCode_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TeamCode_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string PaymentType
        {
            get
            {
                return global::LightSwitchApplication.PaymentRecord.DetailsClass.GetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.PaymentType);
            }
            set
            {
                global::LightSwitchApplication.PaymentRecord.DetailsClass.SetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.PaymentType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PaymentType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PaymentType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PaymentType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return global::LightSwitchApplication.PaymentRecord.DetailsClass.GetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.CreateDate);
            }
            set
            {
                global::LightSwitchApplication.PaymentRecord.DetailsClass.SetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.CreateDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Message
        {
            get
            {
                return global::LightSwitchApplication.PaymentRecord.DetailsClass.GetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.Message);
            }
            set
            {
                global::LightSwitchApplication.PaymentRecord.DetailsClass.SetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.Message, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Message_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Message_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Message_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DonorName
        {
            get
            {
                return global::LightSwitchApplication.PaymentRecord.DetailsClass.GetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.DonorName);
            }
            set
            {
                global::LightSwitchApplication.PaymentRecord.DetailsClass.SetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.DonorName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DonorName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DonorName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DonorName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Anonymous
        {
            get
            {
                return global::LightSwitchApplication.PaymentRecord.DetailsClass.GetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.Anonymous);
            }
            set
            {
                global::LightSwitchApplication.PaymentRecord.DetailsClass.SetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.Anonymous, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Anonymous_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Anonymous_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Anonymous_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int TransactionID
        {
            get
            {
                return global::LightSwitchApplication.PaymentRecord.DetailsClass.GetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.TransactionID);
            }
            set
            {
                global::LightSwitchApplication.PaymentRecord.DetailsClass.SetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.TransactionID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TransactionID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TransactionID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TransactionID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int InvoiceID
        {
            get
            {
                return global::LightSwitchApplication.PaymentRecord.DetailsClass.GetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.InvoiceID);
            }
            set
            {
                global::LightSwitchApplication.PaymentRecord.DetailsClass.SetValue(this, global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.InvoiceID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InvoiceID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InvoiceID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InvoiceID_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.PaymentRecord,
                global::LightSwitchApplication.PaymentRecord.DetailsClass,
                global::LightSwitchApplication.PaymentRecord.DetailsClass.IImplementation,
                global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.paymentID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass>.Entry
                __PaymentRecordEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass>.Entry(
                    global::LightSwitchApplication.PaymentRecord.DetailsClass.__PaymentRecord_CreateNew,
                    global::LightSwitchApplication.PaymentRecord.DetailsClass.__PaymentRecord_Created,
                    global::LightSwitchApplication.PaymentRecord.DetailsClass.__PaymentRecord_AllowSaveWithErrors);
            private static global::LightSwitchApplication.PaymentRecord __PaymentRecord_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.PaymentRecord> es)
            {
                return new global::LightSwitchApplication.PaymentRecord(es);
            }
            private static void __PaymentRecord_Created(global::LightSwitchApplication.PaymentRecord e)
            {
                e.PaymentRecord_Created();
            }
            private static bool __PaymentRecord_AllowSaveWithErrors(global::LightSwitchApplication.PaymentRecord e)
            {
                bool result = false;
                e.PaymentRecord_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, int> paymentID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.paymentID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string> PayerEmail
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.PayerEmail) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, double> amount
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.amount) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, double>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string> ConvictEmail
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.ConvictEmail) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string> TeamCode
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.TeamCode) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string> PaymentType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.PaymentType) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, global::System.DateTime> CreateDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.CreateDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string> Message
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.Message) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string> DonorName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.DonorName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, bool> Anonymous
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.Anonymous) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, int> TransactionID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.TransactionID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, int> InvoiceID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties.InvoiceID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, int>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int paymentID { get; }
                new string PayerEmail { get; set; }
                new double amount { get; set; }
                new string ConvictEmail { get; set; }
                new string TeamCode { get; set; }
                new string PaymentType { get; set; }
                new global::System.DateTime CreateDate { get; set; }
                new string Message { get; set; }
                new string DonorName { get; set; }
                new bool Anonymous { get; set; }
                new int TransactionID { get; set; }
                new int InvoiceID { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, int>.Entry
                    paymentID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, int>.Entry(
                        "paymentID",
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._paymentID_Stub,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._paymentID_ComputeIsReadOnly,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._paymentID_Validate,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._paymentID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._paymentID_OnValueChanged);
                private static void _paymentID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PaymentRecord.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, int>.Data> c, global::LightSwitchApplication.PaymentRecord.DetailsClass d, object sf)
                {
                    c(d, ref d._paymentID, sf);
                }
                private static bool _paymentID_ComputeIsReadOnly(global::LightSwitchApplication.PaymentRecord e)
                {
                    bool result = false;
                    e.paymentID_IsReadOnly(ref result);
                    return result;
                }
                private static void _paymentID_Validate(global::LightSwitchApplication.PaymentRecord e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.paymentID_Validate(r);
                }
                private static int _paymentID_GetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d)
                {
                    return d.ImplementationEntity.paymentID;
                }
                private static void _paymentID_OnValueChanged(global::LightSwitchApplication.PaymentRecord e)
                {
                    e.paymentID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Entry
                    PayerEmail = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Entry(
                        "PayerEmail",
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._PayerEmail_Stub,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._PayerEmail_ComputeIsReadOnly,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._PayerEmail_Validate,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._PayerEmail_GetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._PayerEmail_SetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._PayerEmail_OnValueChanged);
                private static void _PayerEmail_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PaymentRecord.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Data> c, global::LightSwitchApplication.PaymentRecord.DetailsClass d, object sf)
                {
                    c(d, ref d._PayerEmail, sf);
                }
                private static bool _PayerEmail_ComputeIsReadOnly(global::LightSwitchApplication.PaymentRecord e)
                {
                    bool result = false;
                    e.PayerEmail_IsReadOnly(ref result);
                    return result;
                }
                private static void _PayerEmail_Validate(global::LightSwitchApplication.PaymentRecord e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PayerEmail_Validate(r);
                }
                private static string _PayerEmail_GetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d)
                {
                    return d.ImplementationEntity.PayerEmail;
                }
                private static void _PayerEmail_SetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d, string v)
                {
                    d.ImplementationEntity.PayerEmail = v;
                }
                private static void _PayerEmail_OnValueChanged(global::LightSwitchApplication.PaymentRecord e)
                {
                    e.PayerEmail_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, double>.Entry
                    amount = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, double>.Entry(
                        "amount",
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._amount_Stub,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._amount_ComputeIsReadOnly,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._amount_Validate,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._amount_GetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._amount_SetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._amount_OnValueChanged);
                private static void _amount_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PaymentRecord.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, double>.Data> c, global::LightSwitchApplication.PaymentRecord.DetailsClass d, object sf)
                {
                    c(d, ref d._amount, sf);
                }
                private static bool _amount_ComputeIsReadOnly(global::LightSwitchApplication.PaymentRecord e)
                {
                    bool result = false;
                    e.amount_IsReadOnly(ref result);
                    return result;
                }
                private static void _amount_Validate(global::LightSwitchApplication.PaymentRecord e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.amount_Validate(r);
                }
                private static double _amount_GetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d)
                {
                    return d.ImplementationEntity.amount;
                }
                private static void _amount_SetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d, double v)
                {
                    d.ImplementationEntity.amount = v;
                }
                private static void _amount_OnValueChanged(global::LightSwitchApplication.PaymentRecord e)
                {
                    e.amount_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Entry
                    ConvictEmail = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Entry(
                        "ConvictEmail",
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._ConvictEmail_Stub,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._ConvictEmail_ComputeIsReadOnly,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._ConvictEmail_Validate,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._ConvictEmail_GetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._ConvictEmail_SetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._ConvictEmail_OnValueChanged);
                private static void _ConvictEmail_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PaymentRecord.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Data> c, global::LightSwitchApplication.PaymentRecord.DetailsClass d, object sf)
                {
                    c(d, ref d._ConvictEmail, sf);
                }
                private static bool _ConvictEmail_ComputeIsReadOnly(global::LightSwitchApplication.PaymentRecord e)
                {
                    bool result = false;
                    e.ConvictEmail_IsReadOnly(ref result);
                    return result;
                }
                private static void _ConvictEmail_Validate(global::LightSwitchApplication.PaymentRecord e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ConvictEmail_Validate(r);
                }
                private static string _ConvictEmail_GetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d)
                {
                    return d.ImplementationEntity.ConvictEmail;
                }
                private static void _ConvictEmail_SetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ConvictEmail = v;
                }
                private static void _ConvictEmail_OnValueChanged(global::LightSwitchApplication.PaymentRecord e)
                {
                    e.ConvictEmail_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Entry
                    TeamCode = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Entry(
                        "TeamCode",
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._TeamCode_Stub,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._TeamCode_ComputeIsReadOnly,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._TeamCode_Validate,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._TeamCode_GetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._TeamCode_SetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._TeamCode_OnValueChanged);
                private static void _TeamCode_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PaymentRecord.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Data> c, global::LightSwitchApplication.PaymentRecord.DetailsClass d, object sf)
                {
                    c(d, ref d._TeamCode, sf);
                }
                private static bool _TeamCode_ComputeIsReadOnly(global::LightSwitchApplication.PaymentRecord e)
                {
                    bool result = false;
                    e.TeamCode_IsReadOnly(ref result);
                    return result;
                }
                private static void _TeamCode_Validate(global::LightSwitchApplication.PaymentRecord e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TeamCode_Validate(r);
                }
                private static string _TeamCode_GetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d)
                {
                    return d.ImplementationEntity.TeamCode;
                }
                private static void _TeamCode_SetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d, string v)
                {
                    d.ImplementationEntity.TeamCode = v;
                }
                private static void _TeamCode_OnValueChanged(global::LightSwitchApplication.PaymentRecord e)
                {
                    e.TeamCode_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Entry
                    PaymentType = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Entry(
                        "PaymentType",
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._PaymentType_Stub,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._PaymentType_ComputeIsReadOnly,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._PaymentType_Validate,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._PaymentType_GetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._PaymentType_SetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._PaymentType_OnValueChanged);
                private static void _PaymentType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PaymentRecord.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Data> c, global::LightSwitchApplication.PaymentRecord.DetailsClass d, object sf)
                {
                    c(d, ref d._PaymentType, sf);
                }
                private static bool _PaymentType_ComputeIsReadOnly(global::LightSwitchApplication.PaymentRecord e)
                {
                    bool result = false;
                    e.PaymentType_IsReadOnly(ref result);
                    return result;
                }
                private static void _PaymentType_Validate(global::LightSwitchApplication.PaymentRecord e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PaymentType_Validate(r);
                }
                private static string _PaymentType_GetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d)
                {
                    return d.ImplementationEntity.PaymentType;
                }
                private static void _PaymentType_SetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d, string v)
                {
                    d.ImplementationEntity.PaymentType = v;
                }
                private static void _PaymentType_OnValueChanged(global::LightSwitchApplication.PaymentRecord e)
                {
                    e.PaymentType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, global::System.DateTime>.Entry
                    CreateDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, global::System.DateTime>.Entry(
                        "CreateDate",
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._CreateDate_Stub,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._CreateDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._CreateDate_Validate,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._CreateDate_GetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._CreateDate_SetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._CreateDate_OnValueChanged);
                private static void _CreateDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PaymentRecord.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.PaymentRecord.DetailsClass d, object sf)
                {
                    c(d, ref d._CreateDate, sf);
                }
                private static bool _CreateDate_ComputeIsReadOnly(global::LightSwitchApplication.PaymentRecord e)
                {
                    bool result = false;
                    e.CreateDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreateDate_Validate(global::LightSwitchApplication.PaymentRecord e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreateDate_Validate(r);
                }
                private static global::System.DateTime _CreateDate_GetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d)
                {
                    return d.ImplementationEntity.CreateDate;
                }
                private static void _CreateDate_SetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.CreateDate = global::LightSwitchApplication.PaymentRecord.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _CreateDate_OnValueChanged(global::LightSwitchApplication.PaymentRecord e)
                {
                    e.CreateDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Entry
                    Message = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Entry(
                        "Message",
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._Message_Stub,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._Message_ComputeIsReadOnly,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._Message_Validate,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._Message_GetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._Message_SetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._Message_OnValueChanged);
                private static void _Message_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PaymentRecord.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Data> c, global::LightSwitchApplication.PaymentRecord.DetailsClass d, object sf)
                {
                    c(d, ref d._Message, sf);
                }
                private static bool _Message_ComputeIsReadOnly(global::LightSwitchApplication.PaymentRecord e)
                {
                    bool result = false;
                    e.Message_IsReadOnly(ref result);
                    return result;
                }
                private static void _Message_Validate(global::LightSwitchApplication.PaymentRecord e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Message_Validate(r);
                }
                private static string _Message_GetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d)
                {
                    return d.ImplementationEntity.Message;
                }
                private static void _Message_SetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Message = v;
                }
                private static void _Message_OnValueChanged(global::LightSwitchApplication.PaymentRecord e)
                {
                    e.Message_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Entry
                    DonorName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Entry(
                        "DonorName",
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._DonorName_Stub,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._DonorName_ComputeIsReadOnly,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._DonorName_Validate,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._DonorName_GetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._DonorName_SetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._DonorName_OnValueChanged);
                private static void _DonorName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PaymentRecord.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Data> c, global::LightSwitchApplication.PaymentRecord.DetailsClass d, object sf)
                {
                    c(d, ref d._DonorName, sf);
                }
                private static bool _DonorName_ComputeIsReadOnly(global::LightSwitchApplication.PaymentRecord e)
                {
                    bool result = false;
                    e.DonorName_IsReadOnly(ref result);
                    return result;
                }
                private static void _DonorName_Validate(global::LightSwitchApplication.PaymentRecord e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DonorName_Validate(r);
                }
                private static string _DonorName_GetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d)
                {
                    return d.ImplementationEntity.DonorName;
                }
                private static void _DonorName_SetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d, string v)
                {
                    d.ImplementationEntity.DonorName = v;
                }
                private static void _DonorName_OnValueChanged(global::LightSwitchApplication.PaymentRecord e)
                {
                    e.DonorName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, bool>.Entry
                    Anonymous = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, bool>.Entry(
                        "Anonymous",
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._Anonymous_Stub,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._Anonymous_ComputeIsReadOnly,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._Anonymous_Validate,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._Anonymous_GetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._Anonymous_SetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._Anonymous_OnValueChanged);
                private static void _Anonymous_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PaymentRecord.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, bool>.Data> c, global::LightSwitchApplication.PaymentRecord.DetailsClass d, object sf)
                {
                    c(d, ref d._Anonymous, sf);
                }
                private static bool _Anonymous_ComputeIsReadOnly(global::LightSwitchApplication.PaymentRecord e)
                {
                    bool result = false;
                    e.Anonymous_IsReadOnly(ref result);
                    return result;
                }
                private static void _Anonymous_Validate(global::LightSwitchApplication.PaymentRecord e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Anonymous_Validate(r);
                }
                private static bool _Anonymous_GetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d)
                {
                    return d.ImplementationEntity.Anonymous;
                }
                private static void _Anonymous_SetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.Anonymous = v;
                }
                private static void _Anonymous_OnValueChanged(global::LightSwitchApplication.PaymentRecord e)
                {
                    e.Anonymous_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, int>.Entry
                    TransactionID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, int>.Entry(
                        "TransactionID",
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._TransactionID_Stub,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._TransactionID_ComputeIsReadOnly,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._TransactionID_Validate,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._TransactionID_GetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._TransactionID_SetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._TransactionID_OnValueChanged);
                private static void _TransactionID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PaymentRecord.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, int>.Data> c, global::LightSwitchApplication.PaymentRecord.DetailsClass d, object sf)
                {
                    c(d, ref d._TransactionID, sf);
                }
                private static bool _TransactionID_ComputeIsReadOnly(global::LightSwitchApplication.PaymentRecord e)
                {
                    bool result = false;
                    e.TransactionID_IsReadOnly(ref result);
                    return result;
                }
                private static void _TransactionID_Validate(global::LightSwitchApplication.PaymentRecord e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TransactionID_Validate(r);
                }
                private static int _TransactionID_GetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d)
                {
                    return d.ImplementationEntity.TransactionID;
                }
                private static void _TransactionID_SetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d, int v)
                {
                    d.ImplementationEntity.TransactionID = v;
                }
                private static void _TransactionID_OnValueChanged(global::LightSwitchApplication.PaymentRecord e)
                {
                    e.TransactionID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, int>.Entry
                    InvoiceID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, int>.Entry(
                        "InvoiceID",
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._InvoiceID_Stub,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._InvoiceID_ComputeIsReadOnly,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._InvoiceID_Validate,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._InvoiceID_GetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._InvoiceID_SetImplementationValue,
                        global::LightSwitchApplication.PaymentRecord.DetailsClass.PropertySetProperties._InvoiceID_OnValueChanged);
                private static void _InvoiceID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PaymentRecord.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, int>.Data> c, global::LightSwitchApplication.PaymentRecord.DetailsClass d, object sf)
                {
                    c(d, ref d._InvoiceID, sf);
                }
                private static bool _InvoiceID_ComputeIsReadOnly(global::LightSwitchApplication.PaymentRecord e)
                {
                    bool result = false;
                    e.InvoiceID_IsReadOnly(ref result);
                    return result;
                }
                private static void _InvoiceID_Validate(global::LightSwitchApplication.PaymentRecord e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.InvoiceID_Validate(r);
                }
                private static int _InvoiceID_GetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d)
                {
                    return d.ImplementationEntity.InvoiceID;
                }
                private static void _InvoiceID_SetImplementationValue(global::LightSwitchApplication.PaymentRecord.DetailsClass d, int v)
                {
                    d.ImplementationEntity.InvoiceID = v;
                }
                private static void _InvoiceID_OnValueChanged(global::LightSwitchApplication.PaymentRecord e)
                {
                    e.InvoiceID_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, int>.Data _paymentID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Data _PayerEmail;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, double>.Data _amount;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Data _ConvictEmail;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Data _TeamCode;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Data _PaymentType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, global::System.DateTime>.Data _CreateDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Data _Message;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, string>.Data _DonorName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, bool>.Data _Anonymous;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, int>.Data _TransactionID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PaymentRecord, global::LightSwitchApplication.PaymentRecord.DetailsClass, int>.Data _InvoiceID;
            
        }
    
        #endregion
    }
    
    #endregion
}
