

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class Convict : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Convict entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Convict()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Convict(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Convict> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Convict.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Convict_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Convict_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Email
        {
            get
            {
                return global::LightSwitchApplication.Convict.DetailsClass.GetValue(this, global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.Email);
            }
            set
            {
                global::LightSwitchApplication.Convict.DetailsClass.SetValue(this, global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.Email, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ConvictCode
        {
            get
            {
                return global::LightSwitchApplication.Convict.DetailsClass.GetValue(this, global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.ConvictCode);
            }
            set
            {
                global::LightSwitchApplication.Convict.DetailsClass.SetValue(this, global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.ConvictCode, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ConvictCode_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ConvictCode_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ConvictCode_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.Convict.DetailsClass.GetValue(this, global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.Convict.DetailsClass.SetValue(this, global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ProfileURL
        {
            get
            {
                return global::LightSwitchApplication.Convict.DetailsClass.GetValue(this, global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.ProfileURL);
            }
            set
            {
                global::LightSwitchApplication.Convict.DetailsClass.SetValue(this, global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.ProfileURL, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProfileURL_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProfileURL_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProfileURL_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TeamCode
        {
            get
            {
                return global::LightSwitchApplication.Convict.DetailsClass.GetValue(this, global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.TeamCode);
            }
            set
            {
                global::LightSwitchApplication.Convict.DetailsClass.SetValue(this, global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.TeamCode, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TeamCode_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TeamCode_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TeamCode_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TeamType
        {
            get
            {
                return global::LightSwitchApplication.Convict.DetailsClass.GetValue(this, global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.TeamType);
            }
            set
            {
                global::LightSwitchApplication.Convict.DetailsClass.SetValue(this, global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.TeamType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TeamType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TeamType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TeamType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return global::LightSwitchApplication.Convict.DetailsClass.GetValue(this, global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.CreateDate);
            }
            set
            {
                global::LightSwitchApplication.Convict.DetailsClass.SetValue(this, global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.CreateDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return global::LightSwitchApplication.Convict.DetailsClass.GetValue(this, global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.ModifiedDate);
            }
            set
            {
                global::LightSwitchApplication.Convict.DetailsClass.SetValue(this, global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.ModifiedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Total
        {
            get
            {
                return global::LightSwitchApplication.Convict.DetailsClass.GetValue(this, global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.Total);
            }
            set
            {
                global::LightSwitchApplication.Convict.DetailsClass.SetValue(this, global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.Total, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Total_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Total_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Total_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Convict,
                global::LightSwitchApplication.Convict.DetailsClass,
                global::LightSwitchApplication.Convict.DetailsClass.IImplementation,
                global::LightSwitchApplication.Convict.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.Email;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass>.Entry
                __ConvictEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass>.Entry(
                    global::LightSwitchApplication.Convict.DetailsClass.__Convict_CreateNew,
                    global::LightSwitchApplication.Convict.DetailsClass.__Convict_Created,
                    global::LightSwitchApplication.Convict.DetailsClass.__Convict_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Convict __Convict_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Convict> es)
            {
                return new global::LightSwitchApplication.Convict(es);
            }
            private static void __Convict_Created(global::LightSwitchApplication.Convict e)
            {
                e.Convict_Created();
            }
            private static bool __Convict_AllowSaveWithErrors(global::LightSwitchApplication.Convict e)
            {
                bool result = false;
                e.Convict_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Convict.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string> Email
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.Email) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string> ConvictCode
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.ConvictCode) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string> ProfileURL
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.ProfileURL) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string> TeamCode
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.TeamCode) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string> TeamType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.TeamType) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, global::System.DateTime> CreateDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.CreateDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, global::System.DateTime> ModifiedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.ModifiedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string> Total
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties.Total) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new string Email { get; set; }
                new string ConvictCode { get; set; }
                new string Name { get; set; }
                new string ProfileURL { get; set; }
                new string TeamCode { get; set; }
                new string TeamType { get; set; }
                new global::System.DateTime CreateDate { get; set; }
                new global::System.DateTime ModifiedDate { get; set; }
                new string Total { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Entry
                    Email = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Entry(
                        "Email",
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._Email_Stub,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._Email_ComputeIsReadOnly,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._Email_Validate,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._Email_GetImplementationValue,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._Email_SetImplementationValue,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._Email_OnValueChanged);
                private static void _Email_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Convict.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Data> c, global::LightSwitchApplication.Convict.DetailsClass d, object sf)
                {
                    c(d, ref d._Email, sf);
                }
                private static bool _Email_ComputeIsReadOnly(global::LightSwitchApplication.Convict e)
                {
                    bool result = false;
                    e.Email_IsReadOnly(ref result);
                    return result;
                }
                private static void _Email_Validate(global::LightSwitchApplication.Convict e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Email_Validate(r);
                }
                private static string _Email_GetImplementationValue(global::LightSwitchApplication.Convict.DetailsClass d)
                {
                    return d.ImplementationEntity.Email;
                }
                private static void _Email_SetImplementationValue(global::LightSwitchApplication.Convict.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Email = v;
                }
                private static void _Email_OnValueChanged(global::LightSwitchApplication.Convict e)
                {
                    e.Email_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Entry
                    ConvictCode = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Entry(
                        "ConvictCode",
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._ConvictCode_Stub,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._ConvictCode_ComputeIsReadOnly,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._ConvictCode_Validate,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._ConvictCode_GetImplementationValue,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._ConvictCode_SetImplementationValue,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._ConvictCode_OnValueChanged);
                private static void _ConvictCode_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Convict.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Data> c, global::LightSwitchApplication.Convict.DetailsClass d, object sf)
                {
                    c(d, ref d._ConvictCode, sf);
                }
                private static bool _ConvictCode_ComputeIsReadOnly(global::LightSwitchApplication.Convict e)
                {
                    bool result = false;
                    e.ConvictCode_IsReadOnly(ref result);
                    return result;
                }
                private static void _ConvictCode_Validate(global::LightSwitchApplication.Convict e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ConvictCode_Validate(r);
                }
                private static string _ConvictCode_GetImplementationValue(global::LightSwitchApplication.Convict.DetailsClass d)
                {
                    return d.ImplementationEntity.ConvictCode;
                }
                private static void _ConvictCode_SetImplementationValue(global::LightSwitchApplication.Convict.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ConvictCode = v;
                }
                private static void _ConvictCode_OnValueChanged(global::LightSwitchApplication.Convict e)
                {
                    e.ConvictCode_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Convict.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Data> c, global::LightSwitchApplication.Convict.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.Convict e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.Convict e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.Convict.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.Convict.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.Convict e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Entry
                    ProfileURL = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Entry(
                        "ProfileURL",
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._ProfileURL_Stub,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._ProfileURL_ComputeIsReadOnly,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._ProfileURL_Validate,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._ProfileURL_GetImplementationValue,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._ProfileURL_SetImplementationValue,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._ProfileURL_OnValueChanged);
                private static void _ProfileURL_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Convict.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Data> c, global::LightSwitchApplication.Convict.DetailsClass d, object sf)
                {
                    c(d, ref d._ProfileURL, sf);
                }
                private static bool _ProfileURL_ComputeIsReadOnly(global::LightSwitchApplication.Convict e)
                {
                    bool result = false;
                    e.ProfileURL_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProfileURL_Validate(global::LightSwitchApplication.Convict e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProfileURL_Validate(r);
                }
                private static string _ProfileURL_GetImplementationValue(global::LightSwitchApplication.Convict.DetailsClass d)
                {
                    return d.ImplementationEntity.ProfileURL;
                }
                private static void _ProfileURL_SetImplementationValue(global::LightSwitchApplication.Convict.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ProfileURL = v;
                }
                private static void _ProfileURL_OnValueChanged(global::LightSwitchApplication.Convict e)
                {
                    e.ProfileURL_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Entry
                    TeamCode = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Entry(
                        "TeamCode",
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._TeamCode_Stub,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._TeamCode_ComputeIsReadOnly,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._TeamCode_Validate,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._TeamCode_GetImplementationValue,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._TeamCode_SetImplementationValue,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._TeamCode_OnValueChanged);
                private static void _TeamCode_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Convict.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Data> c, global::LightSwitchApplication.Convict.DetailsClass d, object sf)
                {
                    c(d, ref d._TeamCode, sf);
                }
                private static bool _TeamCode_ComputeIsReadOnly(global::LightSwitchApplication.Convict e)
                {
                    bool result = false;
                    e.TeamCode_IsReadOnly(ref result);
                    return result;
                }
                private static void _TeamCode_Validate(global::LightSwitchApplication.Convict e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TeamCode_Validate(r);
                }
                private static string _TeamCode_GetImplementationValue(global::LightSwitchApplication.Convict.DetailsClass d)
                {
                    return d.ImplementationEntity.TeamCode;
                }
                private static void _TeamCode_SetImplementationValue(global::LightSwitchApplication.Convict.DetailsClass d, string v)
                {
                    d.ImplementationEntity.TeamCode = v;
                }
                private static void _TeamCode_OnValueChanged(global::LightSwitchApplication.Convict e)
                {
                    e.TeamCode_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Entry
                    TeamType = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Entry(
                        "TeamType",
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._TeamType_Stub,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._TeamType_ComputeIsReadOnly,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._TeamType_Validate,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._TeamType_GetImplementationValue,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._TeamType_SetImplementationValue,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._TeamType_OnValueChanged);
                private static void _TeamType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Convict.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Data> c, global::LightSwitchApplication.Convict.DetailsClass d, object sf)
                {
                    c(d, ref d._TeamType, sf);
                }
                private static bool _TeamType_ComputeIsReadOnly(global::LightSwitchApplication.Convict e)
                {
                    bool result = false;
                    e.TeamType_IsReadOnly(ref result);
                    return result;
                }
                private static void _TeamType_Validate(global::LightSwitchApplication.Convict e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TeamType_Validate(r);
                }
                private static string _TeamType_GetImplementationValue(global::LightSwitchApplication.Convict.DetailsClass d)
                {
                    return d.ImplementationEntity.TeamType;
                }
                private static void _TeamType_SetImplementationValue(global::LightSwitchApplication.Convict.DetailsClass d, string v)
                {
                    d.ImplementationEntity.TeamType = v;
                }
                private static void _TeamType_OnValueChanged(global::LightSwitchApplication.Convict e)
                {
                    e.TeamType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, global::System.DateTime>.Entry
                    CreateDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, global::System.DateTime>.Entry(
                        "CreateDate",
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._CreateDate_Stub,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._CreateDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._CreateDate_Validate,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._CreateDate_GetImplementationValue,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._CreateDate_SetImplementationValue,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._CreateDate_OnValueChanged);
                private static void _CreateDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Convict.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Convict.DetailsClass d, object sf)
                {
                    c(d, ref d._CreateDate, sf);
                }
                private static bool _CreateDate_ComputeIsReadOnly(global::LightSwitchApplication.Convict e)
                {
                    bool result = false;
                    e.CreateDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreateDate_Validate(global::LightSwitchApplication.Convict e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreateDate_Validate(r);
                }
                private static global::System.DateTime _CreateDate_GetImplementationValue(global::LightSwitchApplication.Convict.DetailsClass d)
                {
                    return d.ImplementationEntity.CreateDate;
                }
                private static void _CreateDate_SetImplementationValue(global::LightSwitchApplication.Convict.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.CreateDate = global::LightSwitchApplication.Convict.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _CreateDate_OnValueChanged(global::LightSwitchApplication.Convict e)
                {
                    e.CreateDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, global::System.DateTime>.Entry
                    ModifiedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, global::System.DateTime>.Entry(
                        "ModifiedDate",
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._ModifiedDate_Stub,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._ModifiedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._ModifiedDate_Validate,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._ModifiedDate_GetImplementationValue,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._ModifiedDate_SetImplementationValue,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._ModifiedDate_OnValueChanged);
                private static void _ModifiedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Convict.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Convict.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedDate, sf);
                }
                private static bool _ModifiedDate_ComputeIsReadOnly(global::LightSwitchApplication.Convict e)
                {
                    bool result = false;
                    e.ModifiedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedDate_Validate(global::LightSwitchApplication.Convict e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedDate_Validate(r);
                }
                private static global::System.DateTime _ModifiedDate_GetImplementationValue(global::LightSwitchApplication.Convict.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedDate;
                }
                private static void _ModifiedDate_SetImplementationValue(global::LightSwitchApplication.Convict.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.ModifiedDate = global::LightSwitchApplication.Convict.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ModifiedDate_OnValueChanged(global::LightSwitchApplication.Convict e)
                {
                    e.ModifiedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Entry
                    Total = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Entry(
                        "Total",
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._Total_Stub,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._Total_ComputeIsReadOnly,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._Total_Validate,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._Total_GetImplementationValue,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._Total_SetImplementationValue,
                        global::LightSwitchApplication.Convict.DetailsClass.PropertySetProperties._Total_OnValueChanged);
                private static void _Total_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Convict.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Data> c, global::LightSwitchApplication.Convict.DetailsClass d, object sf)
                {
                    c(d, ref d._Total, sf);
                }
                private static bool _Total_ComputeIsReadOnly(global::LightSwitchApplication.Convict e)
                {
                    bool result = false;
                    e.Total_IsReadOnly(ref result);
                    return result;
                }
                private static void _Total_Validate(global::LightSwitchApplication.Convict e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Total_Validate(r);
                }
                private static string _Total_GetImplementationValue(global::LightSwitchApplication.Convict.DetailsClass d)
                {
                    return d.ImplementationEntity.Total;
                }
                private static void _Total_SetImplementationValue(global::LightSwitchApplication.Convict.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Total = v;
                }
                private static void _Total_OnValueChanged(global::LightSwitchApplication.Convict e)
                {
                    e.Total_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Data _Email;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Data _ConvictCode;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Data _ProfileURL;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Data _TeamCode;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Data _TeamType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, global::System.DateTime>.Data _CreateDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, global::System.DateTime>.Data _ModifiedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Convict, global::LightSwitchApplication.Convict.DetailsClass, string>.Data _Total;
            
        }
    
        #endregion
    }
    
    #endregion
}
