/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/


/* Zero out our tables */
/* ======================================== */
/* ======================================== */
/* Only do this for initial deployment!!!! */
/* Careful as this will destroy on every push */
/* ======================================== */
/* ======================================== */

DELETE FROM Icons
GO
DELETE FROM Menus
GO


/* Add default menus */
SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO
SET IDENTITY_INSERT [dbo].[Menus] ON
INSERT [Menus] (Id, [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (1, N'Start', NULL, NULL, NULL, NULL)
INSERT [Menus] (Id, [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (2, N'Security', NULL, NULL, NULL, NULL)
SET IDENTITY_INSERT [dbo].[Menus] Off
GO

/* ========================================================================= */
/* Default menu tiles are after the icons table */
/* ========================================================================= */

/* Add Icons to the Icons table */
SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO
SET IDENTITY_INSERT [dbo].[Icons] ON
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (1, N'icon-accessibility', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (2, N'icon-accessibility-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (3, N'icon-address-book', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (4, N'icon-air', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (5, N'icon-alarm', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (6, N'icon-alarm-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (7, N'icon-alarm-cancel', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (8, N'icon-alarm-clock', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (9, N'icon-amazon', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (10, N'icon-anchor', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (11, N'icon-android', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (12, N'icon-apple', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (13, N'icon-arrow-down', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (14, N'icon-arrow-down-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (15, N'icon-arrow-down-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (16, N'icon-arrow-down-4', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (17, N'icon-arrow-down-5', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (18, N'icon-arrow-down-left', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (19, N'icon-arrow-down-right', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (20, N'icon-arrow-left', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (21, N'icon-arrow-left-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (22, N'icon-arrow-left-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (23, N'icon-arrow-left-4', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (24, N'icon-arrow-left-5', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (25, N'icon-arrow-right', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (26, N'icon-arrow-right-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (27, N'icon-arrow-right-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (28, N'icon-arrow-right-4', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (29, N'icon-arrow-right-5', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (30, N'icon-arrow-up', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (31, N'icon-arrow-up-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (32, N'icon-arrow-up-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (33, N'icon-arrow-up-4', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (34, N'icon-arrow-up-5', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (35, N'icon-arrow-up-left', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (36, N'icon-arrow-up-right', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (37, N'icon-at', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (38, N'icon-attachment', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (39, N'icon-auction', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (40, N'icon-award-fill', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (41, N'icon-award-stroke', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (42, N'icon-backspace', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (43, N'icon-backspace-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (44, N'icon-barcode', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (45, N'icon-bars', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (46, N'icon-basket', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (47, N'icon-battery', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (48, N'icon-battery-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (49, N'icon-battery-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (50, N'icon-battery-4', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (51, N'icon-battery-5', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (52, N'icon-battery-charging', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (53, N'icon-battery-empty', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (54, N'icon-battery-full', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (55, N'icon-battery-half', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (56, N'icon-beaker', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (57, N'icon-beaker-alt', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (58, N'icon-bell', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (59, N'icon-blocked', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (60, N'icon-blogger', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (61, N'icon-bluetooth', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (62, N'icon-book', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (63, N'icon-bookmark', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (64, N'icon-bookmark-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (65, N'icon-bookmark-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (66, N'icon-bookmark-4', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (67, N'icon-box', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (68, N'icon-box-add', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (69, N'icon-box-remove', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (70, N'icon-briefcase', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (71, N'icon-briefcase-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (72, N'icon-broadcast', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (73, N'icon-bug', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (74, N'icon-bus', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (75, N'icon-busy', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (76, N'icon-cabinet', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (77, N'icon-calculate', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (78, N'icon-calendar', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (79, N'icon-camera', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (80, N'icon-camera-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (81, N'icon-camera-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (82, N'icon-cancel', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (83, N'icon-cancel-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (84, N'icon-cars', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (85, N'icon-cart', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (86, N'icon-cart-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (87, N'icon-cc', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (88, N'icon-cc-by', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (89, N'icon-cc-nc', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (90, N'icon-cc-nc-eu', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (91, N'icon-cc-nc-jp', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (92, N'icon-cc-nd', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (93, N'icon-cc-pd', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (94, N'icon-cc-sa', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (95, N'icon-cc-share', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (96, N'icon-cc-share-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (97, N'icon-cc-zero', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (98, N'icon-Celsius', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (99, N'icon-chart-alt', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (100, N'icon-checkbox', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (101, N'icon-checkbox-partial', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (102, N'icon-checkbox-unchecked', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (103, N'icon-checkmark', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (104, N'icon-chrome', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (105, N'icon-chronometer', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (106, N'icon-clipboard', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (107, N'icon-clipboard-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (108, N'icon-clock', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (109, N'icon-cloud', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (110, N'icon-cloud-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (111, N'icon-cloud-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (112, N'icon-cloud-4', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (113, N'icon-cloud-5', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (114, N'icon-cloud-6', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (115, N'icon-cloud-7', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (116, N'icon-cloudy', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (117, N'icon-cloudy-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (118, N'icon-cloudy-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (119, N'icon-cloudy-4', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (120, N'icon-clubs', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (121, N'icon-code', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (122, N'icon-coffee', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (123, N'icon-cog', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (124, N'icon-coins', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (125, N'icon-comments', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (126, N'icon-comments-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (127, N'icon-comments-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (128, N'icon-comments-4', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (129, N'icon-comments-5', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (130, N'icon-compass', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (131, N'icon-compass-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (132, N'icon-compass-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (133, N'icon-cone', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (134, N'icon-console', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (135, N'icon-copy', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (136, N'icon-credit-card', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (137, N'icon-css3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (138, N'icon-cube', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (139, N'icon-cube-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (140, N'icon-cycle', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (141, N'icon-dashboard', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (142, N'icon-database', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (143, N'icon-delicious', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (144, N'icon-deviantart', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (145, N'icon-diamond', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (146, N'icon-diamonds', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (147, N'icon-diary', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (148, N'icon-direction', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (149, N'icon-discout', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (150, N'icon-dollar', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (151, N'icon-dollar-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (152, N'icon-download', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (153, N'icon-download-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (154, N'icon-drawer', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (155, N'icon-drawer-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (156, N'icon-dribbble', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (157, N'icon-droplet', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (158, N'icon-earth', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (159, N'icon-eject', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (160, N'icon-embed', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (161, N'icon-enter', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (162, N'icon-enter-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (163, N'icon-equalizer', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (164, N'icon-exit', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (165, N'icon-eye', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (166, N'icon-eye-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (167, N'icon-facebook', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (168, N'icon-Fahrenheit', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (169, N'icon-feed', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (170, N'icon-file', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (171, N'icon-file-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (172, N'icon-file-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (173, N'icon-file-4', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (174, N'icon-file-css', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (175, N'icon-file-excel', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (176, N'icon-file-openoffice', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (177, N'icon-file-pdf', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (178, N'icon-file-powerpoint', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (179, N'icon-files', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (180, N'icon-file-word', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (181, N'icon-file-xml', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (182, N'icon-file-zip', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (183, N'icon-film', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (184, N'icon-filter', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (185, N'icon-finder', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (186, N'icon-fire', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (187, N'icon-firefox', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (188, N'icon-first', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (189, N'icon-first-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (190, N'icon-flag', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (191, N'icon-flag-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (192, N'icon-flattr', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (193, N'icon-flickr', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (194, N'icon-flip', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (195, N'icon-flip-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (196, N'icon-floppy', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (197, N'icon-folder', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (198, N'icon-folder-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (199, N'icon-font', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (200, N'icon-forrst', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (201, N'icon-forward', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (202, N'icon-foursquare', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (203, N'icon-fullscreen-alt', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (204, N'icon-fullscreen-exit-alt', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (205, N'icon-gift', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (206, N'icon-git', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (207, N'icon-github', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (208, N'icon-github-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (209, N'icon-github-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (210, N'icon-github-4', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (211, N'icon-github-5', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (212, N'icon-github-6', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (213, N'icon-glasses', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (214, N'icon-glasses-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (215, N'icon-globe', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (216, N'icon-google', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (217, N'icon-google-drive', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (218, N'icon-google-plus', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (219, N'icon-grid', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (220, N'icon-grid-view', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (221, N'icon-hash', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (222, N'icon-headphones', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (223, N'icon-heart', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (224, N'icon-heart-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (225, N'icon-help', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (226, N'icon-help-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (227, N'icon-history', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (228, N'icon-home', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (229, N'icon-html5', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (230, N'icon-html5-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (231, N'icon-IcoMoon', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (232, N'icon-IE', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (233, N'icon-image', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (234, N'icon-info', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (235, N'icon-info-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (236, N'icon-instagram', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (237, N'icon-joomla', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (238, N'icon-key', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (239, N'icon-key-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (240, N'icon-keyboard', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (241, N'icon-lab', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (242, N'icon-lamp', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (243, N'icon-lamp-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (244, N'icon-laptop', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (245, N'icon-last', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (246, N'icon-last-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (247, N'icon-lastfm', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (248, N'icon-layers', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (249, N'icon-layers-alt', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (250, N'icon-left-quote', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (251, N'icon-left-quote-alt', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (252, N'icon-left-to-right', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (253, N'icon-libreoffice', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (254, N'icon-lightning', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (255, N'icon-lightning-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (256, N'icon-lightning-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (257, N'icon-lightning-4', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (258, N'icon-lightning-5', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (259, N'icon-lightning-6', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (260, N'icon-lines', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (261, N'icon-link', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (262, N'icon-link-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (263, N'icon-linkedin', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (264, N'icon-list', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (265, N'icon-loading', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (266, N'icon-loading-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (267, N'icon-location', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (268, N'icon-location-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (269, N'icon-location-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (270, N'icon-locked', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (271, N'icon-locked-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (272, N'icon-loop', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (273, N'icon-mail', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (274, N'icon-mail-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (275, N'icon-medal', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (276, N'icon-medal-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (277, N'icon-menu', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (278, N'icon-meter-fast', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (279, N'icon-meter-medium', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (280, N'icon-meter-slow', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (281, N'icon-mic', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (282, N'icon-minus', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (283, N'icon-minus-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (284, N'icon-mobile', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (285, N'icon-mobile-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (286, N'icon-monitor', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (287, N'icon-monitor-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (288, N'icon-moon', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (289, N'icon-moon-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (290, N'icon-mouse', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (291, N'icon-move', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (292, N'icon-move-horizontal', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (293, N'icon-move-vertical', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (294, N'icon-music', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (295, N'icon-new', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (296, N'icon-newspaper', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (297, N'icon-new-tab', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (298, N'icon-new-tab-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (299, N'icon-next', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (300, N'icon-none', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (301, N'icon-open', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (302, N'icon-opera', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (303, N'icon-paragraph-center', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (304, N'icon-paragraph-justify', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (305, N'icon-paragraph-left', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (306, N'icon-paragraph-right', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (307, N'icon-pause', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (308, N'icon-pause-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (309, N'icon-paypal', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (310, N'icon-pencil', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (311, N'icon-phone', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (312, N'icon-phone-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (313, N'icon-picassa', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (314, N'icon-pictures', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (315, N'icon-pie', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (316, N'icon-pilcrow', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (317, N'icon-pinterest', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (318, N'icon-play', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (319, N'icon-play-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (320, N'icon-play-alt', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (321, N'icon-playlist', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (322, N'icon-plus', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (323, N'icon-plus-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (324, N'icon-pointer', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (325, N'icon-pop-in', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (326, N'icon-pop-out', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (327, N'icon-power', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (328, N'icon-power-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (329, N'icon-previous', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (330, N'icon-printer', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (331, N'icon-puzzle', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (332, N'icon-radio-checked', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (333, N'icon-radio-unchecked', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (334, N'icon-rainbow', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (335, N'icon-rainy', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (336, N'icon-rainy-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (337, N'icon-rainy-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (338, N'icon-rainy-4', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (339, N'icon-record', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (340, N'icon-reddit', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (341, N'icon-redo', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (342, N'icon-remove', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (343, N'icon-reply', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (344, N'icon-reply-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (345, N'icon-resize', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (346, N'icon-right-quote', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (347, N'icon-right-quote-alt', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (348, N'icon-right-to-left', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (349, N'icon-rocket', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (350, N'icon-ruler', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (351, N'icon-safari', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (352, N'icon-sale', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (353, N'icon-satellite', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (354, N'icon-scissors', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (355, N'icon-screen', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (356, N'icon-search', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (357, N'icon-share', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (358, N'icon-share-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (359, N'icon-share-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (360, N'icon-shipping', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (361, N'icon-shit', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (362, N'icon-skype', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (363, N'icon-smiley', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (364, N'icon-snowflake', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (365, N'icon-snowy', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (366, N'icon-snowy-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (367, N'icon-snowy-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (368, N'icon-snowy-4', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (369, N'icon-snowy-5', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (370, N'icon-soundcloud', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (371, N'icon-spades', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (372, N'icon-spin', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (373, N'icon-star', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (374, N'icon-star-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (375, N'icon-star-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (376, N'icon-star-4', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (377, N'icon-stats', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (378, N'icon-stats-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (379, N'icon-stats-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (380, N'icon-stats-up', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (381, N'icon-steering-wheel', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (382, N'icon-stop', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (383, N'icon-stop-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (384, N'icon-stop-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (385, N'icon-stumbleupon', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (386, N'icon-sun', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (387, N'icon-sun-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (388, N'icon-sun-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (389, N'icon-sunrise', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (390, N'icon-support', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (391, N'icon-switch', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (392, N'icon-tab', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (393, N'icon-tab-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (394, N'icon-tablet', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (395, N'icon-tag', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (396, N'icon-target', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (397, N'icon-target-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (398, N'icon-thermometer', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (399, N'icon-thumbs-down', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (400, N'icon-thumbs-up', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (401, N'icon-ticket', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (402, N'icon-tools', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (403, N'icon-tree-view', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (404, N'icon-trophy', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (405, N'icon-tumblr', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (406, N'icon-tux', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (407, N'icon-tv', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (408, N'icon-twitter', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (409, N'icon-type', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (410, N'icon-umbrella', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (411, N'icon-undo', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (412, N'icon-unlocked', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (413, N'icon-upload', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (414, N'icon-upload-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (415, N'icon-upload-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (416, N'icon-user', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (417, N'icon-user-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (418, N'icon-user-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (419, N'icon-vimeo', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (420, N'icon-volume', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (421, N'icon-volume-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (422, N'icon-volume-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (423, N'icon-volume-4', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (424, N'icon-volume-5', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (425, N'icon-volume-6', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (426, N'icon-volume-mute', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (427, N'icon-warning', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (428, N'icon-weather', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (429, N'icon-weather-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (430, N'icon-weather-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (431, N'icon-weather-4', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (432, N'icon-weather-5', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (433, N'icon-wind', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (434, N'icon-window', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (435, N'icon-windows', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (436, N'icon-windy', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (437, N'icon-windy-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (438, N'icon-windy-3', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (439, N'icon-windy-4', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (440, N'icon-windy-5', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (441, N'icon-wordpress', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (442, N'icon-wrench', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (443, N'icon-xing', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (444, N'icon-yahoo', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (445, N'icon-yelp', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (446, N'icon-youtube', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (447, N'icon-zip', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (448, N'icon-zip-2', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (449, N'icon-zoom-in', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Icons] ([Id], [Name], [CreatedBy], [Created], [ModifiedBy], [Modified]) VALUES (450, N'icon-zoom-out', NULL, NULL, NULL, NULL)
SET IDENTITY_INSERT [dbo].[Icons] OFF
Go

/* Add default tiles */
SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO
SET IDENTITY_INSERT [dbo].[MenuTiles] ON
INSERT INTO [dbo].[MenuTiles] ([Id], [Order], [TileColor], [Type], [Name], [Size], [OnClick], [Status], [StatusBgColor], [StatusFgColor], [Badge], [BadgeBgColor], [BadgeFgColor], [IconBgColor], [IconFgColor], [PermissionId], [CreatedBy], [Created], [ModifiedBy], [Modified], [MenuTile_Icon], [MenuTile_Menu]) VALUES (1, 1, N'#1182c5', N'simple', N'Profile', N'default', N'myapp.showProfile();', N'Profile', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 107, 1)
INSERT INTO [dbo].[MenuTiles] ([Id], [Order], [TileColor], [Type], [Name], [Size], [OnClick], [Status], [StatusBgColor], [StatusFgColor], [Badge], [BadgeBgColor], [BadgeFgColor], [IconBgColor], [IconFgColor], [PermissionId], [CreatedBy], [Created], [ModifiedBy], [Modified], [MenuTile_Icon], [MenuTile_Menu]) VALUES (2, 10, N'#06834e', N'simple', N'Icons', N'default', N'myapp.showIconsBrowse();', N'Icons', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 219, 2)
INSERT INTO [dbo].[MenuTiles] ([Id], [Order], [TileColor], [Type], [Name], [Size], [OnClick], [Status], [StatusBgColor], [StatusFgColor], [Badge], [BadgeBgColor], [BadgeFgColor], [IconBgColor], [IconFgColor], [PermissionId], [CreatedBy], [Created], [ModifiedBy], [Modified], [MenuTile_Icon], [MenuTile_Menu]) VALUES (3, 8, N'#90258d', N'simple', N'Menus', N'double', N'myapp.showMenusBrowse();', N'Menu Administration', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 264, 2)
INSERT INTO [dbo].[MenuTiles] ([Id], [Order], [TileColor], [Type], [Name], [Size], [OnClick], [Status], [StatusBgColor], [StatusFgColor], [Badge], [BadgeBgColor], [BadgeFgColor], [IconBgColor], [IconFgColor], [PermissionId], [CreatedBy], [Created], [ModifiedBy], [Modified], [MenuTile_Icon], [MenuTile_Menu]) VALUES (4, 6, N'#6f6c07', N'simple', N'Permissions', N'default', N'myapp.showPermissionsBrowse();', N'Permissions', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 59, 2)
INSERT INTO [dbo].[MenuTiles] ([Id], [Order], [TileColor], [Type], [Name], [Size], [OnClick], [Status], [StatusBgColor], [StatusFgColor], [Badge], [BadgeBgColor], [BadgeFgColor], [IconBgColor], [IconFgColor], [PermissionId], [CreatedBy], [Created], [ModifiedBy], [Modified], [MenuTile_Icon], [MenuTile_Menu]) VALUES (5, 4, N'#9f041e', N'simple', N'Roles', N'default', N'myapp.showRolesBrowse();', N'Roles', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 134, 2)
INSERT INTO [dbo].[MenuTiles] ([Id], [Order], [TileColor], [Type], [Name], [Size], [OnClick], [Status], [StatusBgColor], [StatusFgColor], [Badge], [BadgeBgColor], [BadgeFgColor], [IconBgColor], [IconFgColor], [PermissionId], [CreatedBy], [Created], [ModifiedBy], [Modified], [MenuTile_Icon], [MenuTile_Menu]) VALUES (6, 2, N'#1fb800', N'simple', N'Users', N'double', N'myapp.showUserRegistrationsBrowse();', N'User Registrations', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 2)
INSERT INTO [dbo].[MenuTiles] ([Id], [Order], [TileColor], [Type], [Name], [Size], [OnClick], [Status], [StatusBgColor], [StatusFgColor], [Badge], [BadgeBgColor], [BadgeFgColor], [IconBgColor], [IconFgColor], [PermissionId], [CreatedBy], [Created], [ModifiedBy], [Modified], [MenuTile_Icon], [MenuTile_Menu]) VALUES (7, 99, N'#ff3b00', N'simple', N'Security', N'double', N'myapp.showSecurity();', N'Security', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 270, 1)
SET IDENTITY_INSERT [dbo].[MenuTiles] Off
GO
 
